spring:
  datasource:
    url: jdbc:postgresql://${RAILWAY_DB_HOST:containers-us-west-169.railway.app}:${RAILWAY_DB_PORT:6620}/${RAILWAY_DB_NAME:railway}
    username: ${RAILWAY_DB_USERNAME:postgres}
    password: ${RAILWAY_DB_PASSWORD:g58P3ewfjx2rHuhblNp4}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    servers:
      - url: https://heroes-production.up.railway.app
        description: Servidor de produção



# RAILWAY_DB_HOST = containers-us-west-169.railway.app
# RAILWAY_DB_PORT = 6620
# RAILWAY_DB_NAME = railway
# RAILWAY_DB_USERNAME = postgres
# RAILWAY_DB_PASSWORD = g58P3ewfjx2rHuhblNp4